### ISSUE TITLE
Please add wait_for_update property to your setDefaultConsentState call

### ISSUE THREAD

**Issue by semisight** [termly/gtm-consent-mode-template#1]
For templates in the gallery that [set consent state](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate), we require that `wait_for_update` be specified

https://github.com/termly/gtm-consent-mode-template/blob/1693464c7cda20685047dcbd11eed152d137f6ee/template.tpl#L93

**Comment by jona-termly** [comment]
@semisight let us know if there is anything we need to do to re-submit the template for review?

**Comment by semisight** [comment]
I apologize for the late reply, I've been out of office. One more remaining thing and then you're good to go: this line in metadata.yaml references a commit that's not linked to a branch (?):

https://github.com/termly/gtm-consent-mode-template/blob/a5e11517b3ed389bfb44892ff5249864f9a24719/metadata.yaml#L6

Updating this to `sha: 6a22d182cbf293b348c54a026e895cfc9339e2fc` should work.

**Comment by dkreft-termly** [comment]
@semisight PR submitted: #5

**Comment by dkreft-termly** [comment]
Fix submitted in b7c87a9b5bd7e841a5ce0c63f447df198b5a09b6

**Comment by dkreft-termly** [comment]
Sorry, I suppose that you should be the one to close this ticket, @semisight. :-)

**Comment by jona-termly** [comment]
@semisight now that the template is approved in the template gallery, do you have any insights into how to get listed on the bottom of this support article? https://support.google.com/tagmanager/answer/10718549#consent-types
